cmake_minimum_required(VERSION 3.16)
project(wheeled_real_system LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(hardware_interface REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
add_library(wheeled_real_system SHARED src/real_system.cpp)
target_include_directories(wheeled_real_system PRIVATE include)
ament_target_dependencies(wheeled_real_system hardware_interface pluginlib rclcpp rclcpp_lifecycle)
pluginlib_export_plugin_description_file(hardware_interface wheeled_real_system.xml)
install(TARGETS wheeled_real_system DESTINATION lib)
install(DIRECTORY include/ DESTINATION include)
ament_export_dependencies(hardware_interface pluginlib)
ament_package()
